apiVersion: v1
kind: Service
metadata:
  name: postgres-project-svc
  namespace: project
  labels:
    app: postgres-project
spec:
  selector:
    app: postgres-project
  clusterIP: None
  ports:
  - port: 5432


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-project
  namespace: project
spec:
  selector:
    matchLabels:
      app: postgres-project
  serviceName: postgres-project-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-project
    spec:
      containers:
      - name: postgres
        image: postgres:18-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-project-data-storage
            mountPath: /data
        envFrom:
          - configMapRef:
              name: todo-configmap
  volumeClaimTemplates:
    - metadata:
        name: postgres-project-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
