apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:1.0
          ports:
          - containerPort: 80
          imagePullPolicy: Never
          env:
          - name: PORT
            value: "8080"
          resources:
            limits:
              memory: "256Mi"  # Maximum memory allowed
              cpu: "200m"      # Maximum CPU allowed
            requests:
              memory: "128Mi"  # Initial memory request
              cpu: "100m" 