apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: exercises
spec:
  storageClassName: my-practice-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi