apiVersion: v1
kind: Service
metadata:
  name: postgres-practice-svc
  namespace: exercises
  labels:
    app: postgres-practice
spec:
  selector:
    app: postgres-practice
  clusterIP: None
  ports:
  - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-practice
  namespace: exercises
spec:
  serviceName: postgres-practice-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-practice
  template:
    metadata:
      labels:
        app: postgres-practice
    spec:
      containers:
        - name: postgres-practice
          image: postgres:18-alpine
          ports:
            - name: db-port
              containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /data/pgdata
          volumeMounts:
            - name: postgres-practice-data-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: postgres-practice-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi