apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  labels:
    app: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes:
      #   - name: shared-image
      #     persistentVolumeClaim:
      #       claimName: project-pvc
      containers:
      - name: pingpong
        image: pingpong:1.5
        ports:
        - containerPort: 80
        # volumeMounts:
        # - name: shared-image
        #   mountPath: /usr/src/app/files
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"      # Maximum CPU allowed
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"  
        env:
        # - name: COUNTER_FILE
        #   value: /usr/src/app/files/pingpong-counter.txt
        - name: PORT
          value: "8080"
    